### ISSUE TITLE
MathQuill to MathJS converted by TeX math parser 

### ISSUE THREAD

**Issue by mairakhalil** [davidtranhq/tex-math-parser#1]
Can any one solve my issue? I have used MathQuill now I want to take the output from mathquill and pass it to mathjs but I am getting ireference error.
This is the error **Uncaught ReferenceError: exports is not defined**  When I opened details of this error I got error in **Object.defineProperty(exports, "__esModule", { value: true });**   For this I am using cdn which is **https://cdn.jsdelivr.net/npm/tex-math-parser**. Let me know if some knows the solutions. Thanks

**Comment by davidtranhq** [comment]
Hi! Can you share a code sample of what is giving you this error?

**Comment by mairakhalil** [comment]
@davidtranhq I have solved my problem thanks. It worked for me when I installed it but CDN didn't worked for me.
